#paste or import the sequence (s) to be analysed:
s = "CCGACTACGGGGGGCCCGTTTTAGGGAGTAACGTCTCTCCTTTGGCACGTCTTTAAAGACCTGGCCAAAAGTCGATTCTCCTAGTCTGTAATCCGGTCTACGTAGGAATGGAGCCACAACTATAAGAAACACAGCAAGCGACCATCGCCAGCTGTGCCCAACCCAGAATCTAACCCAGGGTATTTCTCCTGCAGCTCTCGGTGCAATCAATTTCCAACATCCTGTCTATCGAGCCGTAGCTATATTCCTCAGGCTTGGCGATGATGCCCTAAGTTCAAGGATAAAGCGAAGGATGCATATTGATTAACTAATTCTCCTAACTCATGCCGGTGTACAGTATTTGACTGGTCCGAATGATACGCTGGACAACAGTATTACCCCCCGTCTCTTCCTGACGTCTGCAGGGTAATGTATCCAGGGCATTATAACCATGTTACGAGATGGTTAGCTCTCCCGCAAGTCCACTTTATGCGATGCCCGAGTACACGTCGGCTGCCATAGGTCCGGGATCTGAGCGTATCACTCAACACTCTTATTCAGTGCTCTTCAGAACGTGTCTGGTTTTCAATAGCGCCCAATACTATCACACACTCATATACCTTGACCAACCTCTCAGCCGAAGTCAAACACGCATGAGAGACATGTGGGCCCCTAATTCCTGATCCACCGTCTTAGTCTACGTCGGCATAGCATACGCAGGTGGTAACGGTGGGAATAGGTAGCTGGGGTAACACTTTTCTTTTAAACGGGACTGTTGATGCTGCCCTACACCGTTCCGTAGCTTACTGCTAACGACACATTTCCGAATCGCAAATACCGCTGTATCCAA"
A=0
C=0
G=0
T=0

for i in range(len(s)):
    if s[i]=='A':
        A=A+1
    elif s[i]=='C':
        C=C+1
    elif s[i]=='G':
        G=G+1
    else:
        T=T+1

        
print (A, C, G, T)
